[package]
name = "aoc_2015"
version = "1.0.0"
authors = ["Zhora Trush <tensorush@gmail.com>"]
edition = "2018"

[dependencies]
md5 = "0.7.0"
itertools = "0.10.1"
serde_json = "1.0.66"
permutohedron = "0.2.4"